// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: wishlist.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item_Itempriority int32

const (
	Item_LOW    Item_Itempriority = 0
	Item_MEDIUM Item_Itempriority = 50
	Item_HIGH   Item_Itempriority = 100
)

// Enum value maps for Item_Itempriority.
var (
	Item_Itempriority_name = map[int32]string{
		0:   "LOW",
		50:  "MEDIUM",
		100: "HIGH",
	}
	Item_Itempriority_value = map[string]int32{
		"LOW":    0,
		"MEDIUM": 50,
		"HIGH":   100,
	}
)

func (x Item_Itempriority) Enum() *Item_Itempriority {
	p := new(Item_Itempriority)
	*p = x
	return p
}

func (x Item_Itempriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Item_Itempriority) Descriptor() protoreflect.EnumDescriptor {
	return file_wishlist_proto_enumTypes[0].Descriptor()
}

func (Item_Itempriority) Type() protoreflect.EnumType {
	return &file_wishlist_proto_enumTypes[0]
}

func (x Item_Itempriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Item_Itempriority.Descriptor instead.
func (Item_Itempriority) EnumDescriptor() ([]byte, []int) {
	return file_wishlist_proto_rawDescGZIP(), []int{0, 0}
}

type Item_Itemstatus int32

const (
	Item_Inactive Item_Itemstatus = 0
	Item_Active   Item_Itemstatus = 1
)

// Enum value maps for Item_Itemstatus.
var (
	Item_Itemstatus_name = map[int32]string{
		0: "Inactive",
		1: "Active",
	}
	Item_Itemstatus_value = map[string]int32{
		"Inactive": 0,
		"Active":   1,
	}
)

func (x Item_Itemstatus) Enum() *Item_Itemstatus {
	p := new(Item_Itemstatus)
	*p = x
	return p
}

func (x Item_Itemstatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Item_Itemstatus) Descriptor() protoreflect.EnumDescriptor {
	return file_wishlist_proto_enumTypes[1].Descriptor()
}

func (Item_Itemstatus) Type() protoreflect.EnumType {
	return &file_wishlist_proto_enumTypes[1]
}

func (x Item_Itemstatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Item_Itemstatus.Descriptor instead.
func (Item_Itemstatus) EnumDescriptor() ([]byte, []int) {
	return file_wishlist_proto_rawDescGZIP(), []int{0, 1}
}

type Wishlist_Wishliststatus int32

const (
	Wishlist_Inactive Wishlist_Wishliststatus = 0
	Wishlist_Active   Wishlist_Wishliststatus = 1
)

// Enum value maps for Wishlist_Wishliststatus.
var (
	Wishlist_Wishliststatus_name = map[int32]string{
		0: "Inactive",
		1: "Active",
	}
	Wishlist_Wishliststatus_value = map[string]int32{
		"Inactive": 0,
		"Active":   1,
	}
)

func (x Wishlist_Wishliststatus) Enum() *Wishlist_Wishliststatus {
	p := new(Wishlist_Wishliststatus)
	*p = x
	return p
}

func (x Wishlist_Wishliststatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Wishlist_Wishliststatus) Descriptor() protoreflect.EnumDescriptor {
	return file_wishlist_proto_enumTypes[2].Descriptor()
}

func (Wishlist_Wishliststatus) Type() protoreflect.EnumType {
	return &file_wishlist_proto_enumTypes[2]
}

func (x Wishlist_Wishliststatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Wishlist_Wishliststatus.Descriptor instead.
func (Wishlist_Wishliststatus) EnumDescriptor() ([]byte, []int) {
	return file_wishlist_proto_rawDescGZIP(), []int{1, 0}
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Wishlist string            `protobuf:"bytes,2,opt,name=wishlist,proto3" json:"wishlist,omitempty"`
	Name     string            `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Link     string            `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	Price    float64           `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Priority Item_Itempriority `protobuf:"varint,6,opt,name=priority,proto3,enum=grpc.Item_Itempriority" json:"priority,omitempty"`
	Status   Item_Itemstatus   `protobuf:"varint,7,opt,name=status,proto3,enum=grpc.Item_Itemstatus" json:"status,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wishlist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_wishlist_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetWishlist() string {
	if x != nil {
		return x.Wishlist
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Item) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Item) GetPriority() Item_Itempriority {
	if x != nil {
		return x.Priority
	}
	return Item_LOW
}

func (x *Item) GetStatus() Item_Itemstatus {
	if x != nil {
		return x.Status
	}
	return Item_Inactive
}

type Wishlist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status Wishlist_Wishliststatus `protobuf:"varint,3,opt,name=status,proto3,enum=grpc.Wishlist_Wishliststatus" json:"status,omitempty"`
}

func (x *Wishlist) Reset() {
	*x = Wishlist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wishlist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Wishlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wishlist) ProtoMessage() {}

func (x *Wishlist) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wishlist.ProtoReflect.Descriptor instead.
func (*Wishlist) Descriptor() ([]byte, []int) {
	return file_wishlist_proto_rawDescGZIP(), []int{1}
}

func (x *Wishlist) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Wishlist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Wishlist) GetStatus() Wishlist_Wishliststatus {
	if x != nil {
		return x.Status
	}
	return Wishlist_Inactive
}

type CreateWishlistReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wishlist string `protobuf:"bytes,1,opt,name=Wishlist,proto3" json:"Wishlist,omitempty"`
}

func (x *CreateWishlistReq) Reset() {
	*x = CreateWishlistReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wishlist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWishlistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWishlistReq) ProtoMessage() {}

func (x *CreateWishlistReq) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWishlistReq.ProtoReflect.Descriptor instead.
func (*CreateWishlistReq) Descriptor() ([]byte, []int) {
	return file_wishlist_proto_rawDescGZIP(), []int{2}
}

func (x *CreateWishlistReq) GetWishlist() string {
	if x != nil {
		return x.Wishlist
	}
	return ""
}

type CreateWishListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WishlistId string `protobuf:"bytes,1,opt,name=WishlistId,proto3" json:"WishlistId,omitempty"`
}

func (x *CreateWishListRes) Reset() {
	*x = CreateWishListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wishlist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWishListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWishListRes) ProtoMessage() {}

func (x *CreateWishListRes) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWishListRes.ProtoReflect.Descriptor instead.
func (*CreateWishListRes) Descriptor() ([]byte, []int) {
	return file_wishlist_proto_rawDescGZIP(), []int{3}
}

func (x *CreateWishListRes) GetWishlistId() string {
	if x != nil {
		return x.WishlistId
	}
	return ""
}

type AddItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *Item `protobuf:"bytes,2,opt,name=Item,proto3" json:"Item,omitempty"`
}

func (x *AddItemReq) Reset() {
	*x = AddItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wishlist_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemReq) ProtoMessage() {}

func (x *AddItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemReq.ProtoReflect.Descriptor instead.
func (*AddItemReq) Descriptor() ([]byte, []int) {
	return file_wishlist_proto_rawDescGZIP(), []int{4}
}

func (x *AddItemReq) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type AddItemRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId string `protobuf:"bytes,1,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
}

func (x *AddItemRes) Reset() {
	*x = AddItemRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wishlist_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddItemRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRes) ProtoMessage() {}

func (x *AddItemRes) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemRes.ProtoReflect.Descriptor instead.
func (*AddItemRes) Descriptor() ([]byte, []int) {
	return file_wishlist_proto_rawDescGZIP(), []int{5}
}

func (x *AddItemRes) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type ListWishListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WishlistId string `protobuf:"bytes,1,opt,name=WishlistId,proto3" json:"WishlistId,omitempty"`
}

func (x *ListWishListReq) Reset() {
	*x = ListWishListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wishlist_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWishListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWishListReq) ProtoMessage() {}

func (x *ListWishListReq) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWishListReq.ProtoReflect.Descriptor instead.
func (*ListWishListReq) Descriptor() ([]byte, []int) {
	return file_wishlist_proto_rawDescGZIP(), []int{6}
}

func (x *ListWishListReq) GetWishlistId() string {
	if x != nil {
		return x.WishlistId
	}
	return ""
}

type ListWishListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
}

func (x *ListWishListRes) Reset() {
	*x = ListWishListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wishlist_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWishListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWishListRes) ProtoMessage() {}

func (x *ListWishListRes) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWishListRes.ProtoReflect.Descriptor instead.
func (*ListWishListRes) Descriptor() ([]byte, []int) {
	return file_wishlist_proto_rawDescGZIP(), []int{7}
}

func (x *ListWishListRes) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_wishlist_proto protoreflect.FileDescriptor

var file_wishlist_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x77, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0xab, 0x02, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x77, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x77, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c,
	0x69, 0x6e, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x08, 0x70, 0x72, 0x69,
	0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x70, 0x72, 0x69, 0x6f,
	0x72, 0x69, 0x74, 0x79, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x2d,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2d, 0x0a,
	0x0c, 0x49, 0x74, 0x65, 0x6d, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x07, 0x0a,
	0x03, 0x4c, 0x4f, 0x57, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x45, 0x44, 0x49, 0x55, 0x4d,
	0x10, 0x32, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x49, 0x47, 0x48, 0x10, 0x64, 0x22, 0x26, 0x0a, 0x0a,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x6e,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x10, 0x01, 0x22, 0x91, 0x01, 0x0a, 0x08, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x57, 0x69, 0x73,
	0x68, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2a, 0x0a, 0x0e,
	0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0c,
	0x0a, 0x08, 0x49, 0x6e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x10, 0x01, 0x22, 0x2f, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a,
	0x08, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x33, 0x0a, 0x11, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x57, 0x69, 0x73, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x22, 0x2c,
	0x0a, 0x0a, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x04,
	0x49, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x24, 0x0a, 0x0a,
	0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x74,
	0x65, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x49, 0x74, 0x65, 0x6d,
	0x49, 0x64, 0x22, 0x31, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x73, 0x68, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x57, 0x69, 0x73, 0x68, 0x6c,
	0x69, 0x73, 0x74, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x73,
	0x68, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x32, 0xae, 0x01, 0x0a, 0x0f, 0x57,
	0x69, 0x73, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a,
	0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x69, 0x73, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57,
	0x69, 0x73, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x03, 0x41, 0x64,
	0x64, 0x12, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x65, 0x73, 0x12, 0x34, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x15, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x69, 0x73, 0x68, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x57, 0x69, 0x73, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x42, 0x25, 0x5a, 0x23, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x6e, 0x67, 0x63, 0x65, 0x6c,
	0x6f, 0x2f, 0x53, 0x49, 0x4f, 0x50, 0x31, 0x5f, 0x67, 0x52, 0x50, 0x43, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wishlist_proto_rawDescOnce sync.Once
	file_wishlist_proto_rawDescData = file_wishlist_proto_rawDesc
)

func file_wishlist_proto_rawDescGZIP() []byte {
	file_wishlist_proto_rawDescOnce.Do(func() {
		file_wishlist_proto_rawDescData = protoimpl.X.CompressGZIP(file_wishlist_proto_rawDescData)
	})
	return file_wishlist_proto_rawDescData
}

var file_wishlist_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_wishlist_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_wishlist_proto_goTypes = []interface{}{
	(Item_Itempriority)(0),       // 0: grpc.Item.Itempriority
	(Item_Itemstatus)(0),         // 1: grpc.Item.Itemstatus
	(Wishlist_Wishliststatus)(0), // 2: grpc.Wishlist.Wishliststatus
	(*Item)(nil),                 // 3: grpc.Item
	(*Wishlist)(nil),             // 4: grpc.Wishlist
	(*CreateWishlistReq)(nil),    // 5: grpc.CreateWishlistReq
	(*CreateWishListRes)(nil),    // 6: grpc.CreateWishListRes
	(*AddItemReq)(nil),           // 7: grpc.AddItemReq
	(*AddItemRes)(nil),           // 8: grpc.AddItemRes
	(*ListWishListReq)(nil),      // 9: grpc.ListWishListReq
	(*ListWishListRes)(nil),      // 10: grpc.ListWishListRes
}
var file_wishlist_proto_depIdxs = []int32{
	0,  // 0: grpc.Item.priority:type_name -> grpc.Item.Itempriority
	1,  // 1: grpc.Item.status:type_name -> grpc.Item.Itemstatus
	2,  // 2: grpc.Wishlist.status:type_name -> grpc.Wishlist.Wishliststatus
	3,  // 3: grpc.AddItemReq.Item:type_name -> grpc.Item
	3,  // 4: grpc.ListWishListRes.Items:type_name -> grpc.Item
	5,  // 5: grpc.WishListService.Create:input_type -> grpc.CreateWishlistReq
	7,  // 6: grpc.WishListService.Add:input_type -> grpc.AddItemReq
	9,  // 7: grpc.WishListService.List:input_type -> grpc.ListWishListReq
	6,  // 8: grpc.WishListService.Create:output_type -> grpc.CreateWishListRes
	8,  // 9: grpc.WishListService.Add:output_type -> grpc.AddItemRes
	10, // 10: grpc.WishListService.List:output_type -> grpc.ListWishListRes
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_wishlist_proto_init() }
func file_wishlist_proto_init() {
	if File_wishlist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wishlist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wishlist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Wishlist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wishlist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWishlistReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wishlist_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWishListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wishlist_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wishlist_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddItemRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wishlist_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWishListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wishlist_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWishListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wishlist_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wishlist_proto_goTypes,
		DependencyIndexes: file_wishlist_proto_depIdxs,
		EnumInfos:         file_wishlist_proto_enumTypes,
		MessageInfos:      file_wishlist_proto_msgTypes,
	}.Build()
	File_wishlist_proto = out.File
	file_wishlist_proto_rawDesc = nil
	file_wishlist_proto_goTypes = nil
	file_wishlist_proto_depIdxs = nil
}
